# Generated by Django 4.0.4 on 2022-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_animal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
