# Generated by Django 4.0.4 on 2022-05-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_cadeira_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=155)),
                ('data', models.DateField()),
            ],
        ),
    ]
