# Generated by Django 4.0.4 on 2022-05-24 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_pontuacaoquizz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=100)),
                ('link_linkedin', models.CharField(max_length=100)),
                ('link_lusofona', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.date(2022, 5, 24)),
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_titulo', models.CharField(max_length=100)),
                ('proj_descricao', models.CharField(max_length=100)),
                ('proj_imagem', models.CharField(max_length=100)),
                ('proj_ano', models.CharField(max_length=100)),
                ('proj_cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_pratica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='docente_pratica', to='portfolio.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='docente_teorica', to='portfolio.professor'),
            preserve_default=False,
        ),
    ]
