# Generated by Django 4.0.4 on 2022-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_projeto_alter_post_data_delete_projetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tec_nome', models.CharField(max_length=50)),
                ('tec_acronimo', models.CharField(max_length=50)),
                ('tec_ano_criacao', models.CharField(max_length=4)),
                ('tec_logotipo', models.ImageField(upload_to='')),
                ('tec_site_link', models.CharField(max_length=100)),
                ('tec_descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
