# Generated by Django 4.0.4 on 2022-05-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_tecnologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('link_linkedin', models.CharField(max_length=100)),
                ('link_instagram', models.CharField(max_length=100)),
                ('link_github', models.CharField(max_length=100)),
                ('foto_aluno', models.ImageField(upload_to='')),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
    ]
