# Generated by Django 4.0.4 on 2022-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_noticia_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
    ]
