# Generated by Django 4.0.4 on 2022-05-27 13:39

import datetime
from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_informacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto_aluno',
            field=models.ImageField(upload_to=portfolio.models.resolution_path),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to=portfolio.models.resolution_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.date(2022, 5, 27)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='proj_imagem',
            field=models.ImageField(upload_to=portfolio.models.resolution_path),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='tec_logotipo',
            field=models.ImageField(upload_to=portfolio.models.resolution_path),
        ),
    ]
