# Generated by Django 4.0.4 on 2022-05-27 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_informacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.date(2022, 5, 27)),
        ),
    ]
