# Generated by Django 4.0.4 on 2022-06-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_tfc_alter_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfc',
            name='relatorio',
        ),
    ]
